#defaultView:Graph
SELECT ?item ?itemLabel ?linkTo
WHERE
{
  ?item wdt:P279* wd:Q27525351.
  OPTIONAL { ?item ^wdt:P279 ?linkTo }
  SERVICE wikibase:label {bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en,fr" }
}