@startuml flow

rectangle "**download-ontologies.sh**" {

cloud "Wikidata Query Service" as wikidata #palegreen
file musicClasses.rq
file musicDataProperties.rq
file musicObjectProperties.rq
file musicClasses.rdf
file musicDataProperties.rdf
file musicObjectProperties.rdf
file music.owl #palegreen
rectangle "**download-ontologies.py** (part 1 - fetch)" as wd1 #aliceblue
rectangle "**download-ontologies.py** (part 2 - merge)" as wd2 #aliceblue
musicClasses.rq --> wd1
musicDataProperties.rq --> wd1
musicObjectProperties.rq --> wd1
wikidata --> wd1
wd1 --> musicClasses.rdf
wd1 --> musicDataProperties.rdf
wd1 --> musicObjectProperties.rdf
musicClasses.rdf --> wd2
musicDataProperties.rdf --> wd2
musicObjectProperties.rdf --> wd2
wd2 --> music.owl

cloud "Polifonia ontology" as polifonia #palegreen
rectangle "polifonia/**download-ontologies.sh**" as downpolifonia #aliceblue
file namespaces.csv
folder "polifonia/ontology" as polifoniaowl #palegreen
namespaces.csv --> downpolifonia
polifonia --> downpolifonia
downpolifonia --> polifoniaowl
note right of polifoniaowl: See owl-imports-graph.svg for the patches applied to fix errors

rectangle "**get_known_mappings.py**" as get_known_mappings #aliceblue
file "known_mappings.tsv"
file "wikidata/polifonia_wikidata.tsv" as polifonia_wikidata
file "known_mappings.nq" #palegreen
note bottom of known_mappings.nq: Includes some manual matches, mainly for the core module
known_mappings.nq --> get_known_mappings
polifoniaowl --> get_known_mappings
wikidata --> get_known_mappings
get_known_mappings --> known_mappings.tsv
get_known_mappings --> polifonia_wikidata
get_known_mappings --> known_mappings.nq

}

rectangle "Notebook **bertmap_match.ipynb**" as notebook #aliceblue
file "bertmap.yaml" as yml
file "bertmap_repaired_mappings.tsv" as repaired
yml -> notebook
known_mappings.tsv --> notebook
music.owl --> notebook
polifoniaowl --> notebook
notebook --> repaired

file "all_with_bertmap.tsv"
rectangle "**merge_true_with_bertmap.py**" as merge_true_with_bertmap #aliceblue
note left of all_with_bertmap.tsv: Manual (true) matches are added to all classes which have a Bertmap (predicted) match and no known mapping
polifonia_wikidata --> merge_true_with_bertmap
repaired -> merge_true_with_bertmap
merge_true_with_bertmap --> all_with_bertmap.tsv

rectangle "**evaultate_all_with_bertmap.py**" as evaluate #aliceblue
file "report.txt"
all_with_bertmap.tsv --> evaluate
evaluate --> report.txt
@enduml