# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BV9j3aH7JQymq7A9vIYW1Nomk92B6FAQ
"""

!pip3 install torch torchvision torchaudio deeponto

from deeponto.onto import Ontology
from deeponto.align.bertmap import BERTMapPipeline, DEFAULT_CONFIG_FILE

config_file = "bertmap.yaml"
#config_file = DEFAULT_CONFIG_FILE
src_onto_file = "core.owl"
tgt_onto_file = "mo.owl"

config = BERTMapPipeline.load_bertmap_config(config_file)
#BERTMapPipeline.save_bertmap_config(config, "bertmap.yaml")

src_onto = Ontology(src_onto_file)

tgt_onto = Ontology(tgt_onto_file)

bertmap = BERTMapPipeline(src_onto, tgt_onto, config)

!zip -r /content/bertmap-output.zip /content/bertmap/match

!rm -rf /content/bertmap