# -*- coding: utf-8 -*-
"""bertmap_match.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BV9j3aH7JQymq7A9vIYW1Nomk92B6FAQ

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Danysan1/unibo-ke-matching-ontologies/blob/main/music-ontology/bertmap_match.ipynb)
[![Open in Kaggle](https://kaggle.com/static/images/open-in-kaggle.svg)](https://kaggle.com/kernels/welcome?src=https://github.com/Danysan1/unibo-ke-matching-ontologies/blob/main/music-ontology/bertmap_match.ipynb)
[![Open in SageMaker Studio Lab](https://studiolab.sagemaker.aws/studiolab.svg)](https://studiolab.sagemaker.aws/import/github/Danysan1/unibo-ke-matching-ontologies/tree/main/music-ontology/bertmap_match.ipynb)

# Polifonia - MusicOntology alignment with BERTMap
"""

!pip3 install torch torchvision torchaudio deeponto

from deeponto.onto import Ontology
from deeponto.align.bertmap import BERTMapPipeline, DEFAULT_CONFIG_FILE

config_file = "bertmap.yaml"
#config_file = DEFAULT_CONFIG_FILE
src_onto_file = "core.owl"
tgt_onto_file = "mo.owl"

config = BERTMapPipeline.load_bertmap_config(config_file)
#BERTMapPipeline.save_bertmap_config(config, "bertmap.yaml")

src_onto = Ontology(src_onto_file)

tgt_onto = Ontology(tgt_onto_file)

bertmap = BERTMapPipeline(src_onto, tgt_onto, config)

!zip -r /content/bertmap-output.zip /content/bertmap/match

!rm -rf /content/bertmap