@startuml polifonia-ontology-imports

rectangle "https://w3id.org/polifonia/ontology/" {
    [ontology-network] as network
    [bells]
    [cometa]
    [core]
    [music-instrument] as instrument
    [music-algorithm] as algorithm
    [music-annotation] as annotation
    [music-analysis] as analysis
    [music-meta] as meta
    [music-projection] as projection
    [music-representation] as representation
    [organs]
    [source]
    [tunes]
    [jams]
    [algorithm-pattern] as pattern

    network --> bells
    network --> cometa
    network --> core
    network -[#red,thickness=4]-> instrument: broken
    network --> algorithm
    network --> analysis
    network --> annotation
    network --> meta
    network --> projection
    network --> representation
    network --> organs
    network --> source
    network --> tunes
    jams --> projection
    jams --> representation
    meta --> core
    representation --> core

    annotation -[#red,thickness=4]-> jams: broken
    algorithm -[#red,thickness=4]-> pattern: broken
}

rectangle "http://purl.org/ontology/" {
    [mo]
    [ao/core] as ao_core
    [similarity] as musim

    mo --> ao_core
}

rectangle "https://w3id.org/arco/ontology/" {
    [arco]
    [cataloguing-campaign] as campaign
    [catalogue]
    [context-description] as description

    arco --> catalogue
    arco --> campaign
    arco --> description
}

rectangle "https://w3id.org/italia/onto/" {
    [AccessCondition]
    [CLV]
    [COV]
    [MU]
    [RO]
    [SM]
    [TI]
    [l0]
    [POI]

    AccessCondition -[#red]-> l0
    AccessCondition -[#red]-> TI
    TI -[#red,dashed]-> l0 : removed
    TI -[#red]-> MU
    COV --> CLV
    COV -[#red,dashed]-> MU: removed
    COV --> RO
    COV --> SM
    COV -[#red,dashed]-> TI: removed
    COV -[#red,dashed]-> l0: removed
    CLV -[#red,dashed]-> l0: removed
    SM --> AccessCondition
    SM --> POI
    SM -[#red,dashed]-> l0: removed
}

rectangle "http://purl.org/NET/c4dm/" {
    [event]
    [keys]
}

[http://data.doremus.org/ontology#] as doremus

[http://www.w3.org/2004/02/skos/core] as skos

meta -[#red,thickness=4]---> doremus: broken
ao_core -[#red,thickness=4]---> musim: broken

meta ----> mo
bells ----> arco
campaign ----> COV

ao_core -[#red,thickness=4]-> event: sometimes broken
mo -[#red,thickness=4]-> event: sometimes broken
mo -[#red,thickness=4]-> keys: sometimes broken

doremus -[#red]-> skos
representation -[#red,dashed]-> skos: removed

@enduml