@startuml owl-imports-graph

rectangle "https://w3id.org/polifonia/ontology/" {
    [ontology-network] as network #line:red
    [bells] #line:red
    [cometa] #line:red
    [core]
    [music-instrument] as instrument #line:red
    [music-algorithm] as algorithm #line:red
    [music-annotation] as annotation #line:red
    [music-analysis] as analysis
    [music-meta] as meta #line:red
    [music-projection] as projection #line:red
    [music-representation] as representation #line:red
    [organs]
    [source]
    [tunes] #line:red
    [jams] #line:red
    [algorithm-pattern] as pattern

    network --> bells
    network --> cometa
    network --> core
    network -[#red,thickness=4]-> instrument: broken\nfixed
    network --> algorithm
    network --> analysis
    network --> annotation
    network --> meta
    network --> projection
    network --> representation
    network --> organs
    network --> source
    network --> tunes
    jams --> projection
    jams --> representation
    meta --> core
    representation --> core
    algorithm --> representation
    projection --> representation
    instrument --> meta
    instrument --> core
    tunes --> meta
    cometa --> meta

    annotation -[#red,thickness=4]-> jams: broken\nfixed
    algorithm -[#red,thickness=4]-> pattern: broken\nfixed
}

rectangle "http://purl.org/ontology/" {
    [mo] #line:red
    [ao/core] as ao_core #line:red
    [similarity] as musim

    mo --> ao_core
}

rectangle "https://w3id.org/arco/ontology/" {
    [arco] #line:red
    [cataloguing-campaign] as campaign #line:red
    [catalogue]
    [context-description] as description

    arco --> catalogue
    arco --> campaign
    arco --> description
}

rectangle "https://w3id.org/italia/onto/" {
    [AccessCondition] #line:red
    [CLV] #line:red
    [COV] #line:red
    [MU]
    [RO] #line:red
    [SM] #line:red
    [TI] #line:red
    [l0]
    [POI] #line:red

    AccessCondition -[#red]-> l0
    AccessCondition -[#red]-> TI
    TI -[#red,dashed]-> l0 : duplicate\nremoved
    TI -[#red]-> MU
    COV --> CLV
    COV -[#red,dashed]-> MU: duplicate\nremoved
    COV --> RO
    COV --> SM
    COV -[#red,dashed]-> TI: duplicate\nremoved
    COV -[#red,dashed]-> l0: duplicate\nremoved
    CLV -[#red,dashed]-> l0: duplicate\nremoved
    SM --> AccessCondition
    SM --> POI
    SM -[#red,dashed]-> l0: duplicate\nremoved
    POI -[#red,dashed]-> CLV: duplicate\nremoved
    POI -[#red,dashed]-> SM: duplicate\nremoved
    POI -[#red,dashed]-> l0: duplicate\nremoved
    POI -[#red,dashed]-> TI: duplicate\nremoved
    RO -[#red,dashed]-> l0: duplicate\nremoved
    RO -[#red,dashed]-> TI: duplicate\nremoved
}

rectangle "http://purl.org/NET/c4dm/" {
    [event]
    [keys]
}

[http://xmlns.com/foaf/0.1/] as foaf

[http://purl.org/dc/terms/] as terms

[http://data.doremus.org/ontology#] as doremus #line:red

[http://www.w3.org/2004/02/skos/core] as skos

meta -[#red,thickness=4]---> doremus: broken\nfixed
ao_core -[#red,thickness=4]---> musim: broken\nfixed
ao_core -[#red,thickness=4]---> terms: broken\nfixed
mo -[#red,thickness=4]---> foaf: broken\nfixed
ao_core -[#red,thickness=4]---> foaf: broken\nfixed

meta ---> mo
bells ---> arco
campaign ---> COV

ao_core -[#red,thickness=4]--> event: sometimes broken\nfixed
mo -[#red,thickness=4]--> event: sometimes broken\nfixed
mo -[#red,thickness=4]--> keys: sometimes broken\nfixed

doremus -[#red]--> skos
representation -[#red,dashed]--> skos: duplicate\nremoved

@enduml